language: python
env:
  include:
   - python: 2.7
     env:
        - TOXENV=py27-django15
        - TOXENV=py27-django16
        - TOXENV=py27-django17
        - TOXENV=py27-django18
        - TOXENV=py27-django19
        - TOXENV=py27-django110
        - TOXENV=py27-django111
   - python: 3.3
     env:
        - TOXENV=py33-django15
        - TOXENV=py33-django16
        - TOXENV=py33-django17
   - python: 3.4
     env:
        - TOXENV=py34-django15
        - TOXENV=py34-django16
        - TOXENV=py34-django17
        - TOXENV=py34-django18
        - TOXENV=py34-django19
        - TOXENV=py34-django110
        - TOXENV=py34-django111
   - python: 3.5
     env:
        - TOXENV=py35-django18
        - TOXENV=py35-django19
        - TOXENV=py34-django110
        - TOXENV=py34-django111
#  - TOXENV=flake8
#  - TOXENV=sphinx
#  - TOXENV=readme
install:
script:
  - make test
